<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Cookie\Block\Html\Notices $block */
?>
<?php if ($this->helper(\Magento\Cookie\Helper\Cookie::class)->isCookieRestrictionModeEnabled()) : ?>
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie ib-cookie"
         id="notice-cookie-block"
         style="display: none;">
        <div role="document" class="content" tabindex="0">
        	<div class="container container-1140">
				<div class="row py-md-3">
					<div class="copy">
					    <h3>Welcome to iBottles</h3>
						<p>This website uses Cookies to provide you with the best possible experience.<br/><a href="/privacy-policy">Click here to learn about cookie settings</a>.</p>
						<p>By using our website, you consent to our use of cookies in accordance with our Cookie Policy.</p>
					</div>
					<div class="actions">
						<div class="cookie-actions">
							<div>
								<button id="btn-cookie-allow" class="action allow primary">
				                    <span><?= $block->escapeHtml(__('Yes, that\'s ok')) ?></span>
				                </button>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('cookie/index/noCookies'))) ?>"
                }
            }
        }
    </script>
<?php endif; ?>